### ISSUE TITLE
java无法加载主类

### ISSUE THREAD

**Issue by BiliPotato67** [RukkitDev/Rukkit#17]
错误: 找不到或无法加载主类 .net.preferIPv4Stack=true
原因: java.lang.ClassNotFoundException: /net/preferIPv4Stack=true

**Comment by smartcmd** [comment]
请自行检查当前目录下是否存在核心jar文件，这一般不是核心的问题

**Comment by wtbdev** [comment]
启动脚本有问题，现在已经修复了
